import PIL
import PIL.ImageTk

_IMAGE_PATH = "rong/images/{}.png"

RIGHT_POINTING_ARROW = PIL.Image.open(_IMAGE_PATH.format("arrow"))
LEFT_POINTING_ARROW = RIGHT_POINTING_ARROW.rotate(180)
RIGHT_POINTING_BLACK_ARROW = PIL.Image.open(_IMAGE_PATH.format("arrow_black"))
LEFT_POINTING_BLACK_ARROW = RIGHT_POINTING_BLACK_ARROW.rotate(180)
CHECKMARK = PIL.Image.open(_IMAGE_PATH.format("checkmark"))
BLACK_CHECKMARK = PIL.Image.open(_IMAGE_PATH.format("checkmark_black"))
PAUSE_GLYPH = PIL.Image.open(_IMAGE_PATH.format("pause"))
BLACK_PAUSE_GLYPH = PIL.Image.open(_IMAGE_PATH.format("pause_black"))

TKINTER_USABLE_RIGHT_POINTING_ARROW = PIL.ImageTk.PhotoImage(
    RIGHT_POINTING_ARROW
)

TKINTER_USABLE_LEFT_POINTING_ARROW = PIL.ImageTk.PhotoImage(
    LEFT_POINTING_ARROW
)

TKINTER_USABLE_RIGHT_POINTING_BLACK_ARROW = PIL.ImageTk.PhotoImage(
    RIGHT_POINTING_BLACK_ARROW
)

TKINTER_USABLE_LEFT_POINTING_BLACK_ARROW = PIL.ImageTk.PhotoImage(
    LEFT_POINTING_BLACK_ARROW
)

TKINTER_USABLE_CHECKMARK = PIL.ImageTk.PhotoImage(CHECKMARK)
TKINTER_USABLE_BLACK_CHECKMARK = PIL.ImageTk.PhotoImage(BLACK_CHECKMARK)

TKINTER_USEABLE_PAUSE_GLYPH = PIL.ImageTk.PhotoImage(PAUSE_GLYPH)
TKINTER_USEABLE_BLACK_PAUSE_GLYPH = PIL.ImageTk.PhotoImage(BLACK_PAUSE_GLYPH)
